templates/rebuild_i18n.sh.in
Useful when having extra source packages checked out.
=> Find correct locales folder for the project.

plone-4.2.x.cfg, plone-4.3.x.cfg, plone-4.x.cfg, plone-5.0.x.cfg, plone-5.1.x.cfg, plone-5.x.cfg
This allows to see which versions have been picked for the distributions
not pinned on [versions] sections.
See https://pypi.python.org/pypi/zc.buildout/2.5.2#easier-reporting-and-managing-of-versions-new-in-buildout-2-0
I would actually use ``allow-picked-versions = false`` to make buildout fail if there are versions not pinned (that's the only way to get a 100% repeatable buildout), but that can cause way too many breakage...
=> Show picked versions

qa.cfg
Also, we were previously calling 'bin/createcoverage run bin/test'. The 'run bin/test' part is useless, so I removed it.  Maybe it was needed in previous versions.
Also, when createcoverage fails to create a report, bail out early. Otherwise you get confusing grep and bash errors.
We check the $CI environment variable to see if we are on a Continuous Integration machine.  This at least works for Travis:
https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables
In that case, run bin/createcoverage with the `--output-dir` option. This has the side effect of not opening a browser to view the results. This has two reasons:
1. There is no user who can look at the results, so it is useless.
2. Travis fails to kill the browser at the end, so the build never finishes. …
=> On CI environments run createcoverage without opening a browser.

plone-4.0.x.cfg, plone-4.1.x.cfg, plone-4.2.x.cfg, plone-4.3.x.cfg, plone-4.x.cfg, plone-5.0.x.cfg, plone-5.1.x.cfg, plone-5.x.cfg
Since zc.recipe.cmmi 2.0.0 in 2017/06/21, it asks for the newest zc.buildout
release and not all installations can afford that, so let's pin it to 1.3.6.
This version asks for at least zc.buildout 1.4, but since
http://dist.plone.org/release/4.0-latest/versions.cfg asks for 1.4.4, no harm
done.
For more info:
https://community.plone.org/t/zc-recipe-cmmi-2-0-0-released-today-21-06-2017-will-break-all-buildouts-from-plone-because-it-asks-for-zc-buildout-2-9-4-how-should-we-behave/4412/
=> Pin zc.recipe.cmmi to 1.3.6

plone-2.1.x.cfg, plone-2.5.x.cfg, plone-3.1.x.cfg, plone-3.3.1.cfg, plone-3.3.2.cfg, plone-3.3.3.cfg, plone-3.3.4.cfg, plone-3.3.5.cfg, plone-3.3.6.cfg, plone-3.3.x.cfg, plone-3.x.cfg, plone-4.0.x.cfg, plone-4.1.x.cfg, plone-4.2.x.cfg, plone-4.3.x.cfg, plone-4.x.cfg, plone-5.0.x.cfg, plone-5.1.x.cfg, plone-5.x.cfg, qa.cfg
So use https instead of http.
Otherwise no new packages can be found, unless zc.buildout 2.9.5 or higher is used.
See also https://community.plone.org/t/buildout-not-working-disabling-non-https-access-to-apis-on-pypi/5069/
=> Use https://pypi.python.org/simple/ as index.

README.rst, travis-5.2.x.cfg, travis-5.x.cfg
The documentation no longer advertises to use the `buildout-cache.cfg` anymore, which is what happens with the travis configs.
Plus other small fixes in the documentation.
This fixes issue #51.
Additionally we could try to warn current users of the `travis-*.cfg` files by making sure an extra [deprecated part](https://github.com/collective/buildout.plonetest/pull/50#issuecomment-523032360) gets loaded. But we can try that afterwards.
First let's have better documentation.
=> Removed travis-5.2.x.cfg and updated docs

README.rst
sudo should not be used/needed anymore.
See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
Note that one of the items had `sudo: true` in the matrix. I never understood that. It is gone now.
Note that this is hard to test. Theoretically we could add a minimal package in this repository that uses `buildout.plonetest`. I don't see that happening in the near future though.
=> Removed sudo from Travis examples in readme.

README.rst, travis/default.yml
Travis implements sthing similar to ``buildout extends``
See: https://blog.travis-ci.com/2019-11-11-build-config-imports
=> use Travis imports to share build config

.gitignore, qa.cfg
The Plone 5 `setuptools` version is already the required by `flake8`.
In Plone 4, packages should take care of this.
=> Unpinning flake8 in qa.cfg

plone-5.0.x.cfg, plone-5.1.x.cfg, plone-5.2.x.cfg, plone-5.x.cfg
To avoid restart problems, just install the buildout with pip and use in `requirements.txt`, the same versions of `setuptools/buildout` pinned in buildout.
Fix #60
=> Remove `newest = false` to use the default `newest = true`

plone-4.3.x.cfg, plone-4.x.cfg, plone-5.0.x.cfg, plone-5.1.x.cfg, plone-5.2.x.cfg, plone-5.x.cfg
`zipp >= 2.0.0` is not compatible with Python 2. See:
https://github.com/jaraco/zipp/blob/4759ee957b237d9f14b3da1596f66f837fc52d93/setup.cfg#L14
When `zipp` is installed with the current setuptools/buildout combination from https://dist.plone.org/release/5.1-latest/requirements.txt:
```
setuptools==40.8.0
zc.buildout==2.13.1
```
the error occurs:
```
Getting distribution for 'zipp'.
zip_safe flag not set; analyzing archive contents...
While:
Installing.
Getting section code-analysis.
Initializing section code-analysis.
Installing recipe plone.recipe.codeanalysis.
Getting distribution for 'zipp'.
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
File "/home/user/git/collective.elasticsearch/lib/python2.7/site-packages …
```
=> Pin zipp < 2.0.0

qa.cfg
Newest versions aren't compatible with Python 2 See:
https://github.com/timothycrosley/isort/blob/2952db41650211984fe64ac0b856881627e55aeb/pyproject.toml#L27
=> Pin isort = 4.3.20 for Python 2

plone-4.3.x.cfg, plone-4.x.cfg, plone-5.0.x.cfg, plone-5.1.x.cfg, plone-5.2.x.cfg, plone-5.x.cfg
That is the last version that is compatible with 2.7.
Also, 0.45+ pulls in newer version of packages like 'build' and 'pep517', and 'virtualenv'.
For a sample error, see this [easyform run on 5.1](https://travis-ci.org/github/collective/collective.easyform/jobs/743916981).
=> Pin check-manifest to 0.41 on Python 2.7.

plone-5.0.x.cfg
Latest version compatible with Python 2. See:
https://github.com/python/importlib_metadata/blob/530f5da8dd3a255f1198f29ea0126b8b25e644d8/setup.cfg#L14
Other versions of Plone already pin this package.
=> Pinn importlib-metadata = 2.1.1 in Plone 5.0

plone-5.0.x.cfg, plone-5.1.x.cfg, plone-5.2.x.cfg, plone-5.x.cfg, qa.cfg
This is already default value of the buildout versions used by Plone 5.
See:
https://github.com/buildout/buildout/blob/6e00617ec15cb23dd3fd00b159e1df3497b72e1f/src/zc/buildout/easy_install.py#L64-L67
=> Remove index on Plone 5

plone-5.2.x.cfg, plone-5.x.cfg
`check-manifest` and `watchdog` are already pinned at:
https://dist.plone.org/release/5.2-latest/versions.cfg
See:
https://github.com/plone/buildout.coredev/blob/8b7ab4c42a0bd62c106ed67c987d0f3cc4519c16/versions.cfg#L339
=> Removes unnecessary pinns in Plone 5.2

plone-5.0.x.cfg, qa.cfg
The versions of `Zope` used by Plone 5.2, 5.1 and 4.3 already pin a Python 2 compatible version of `configparser`. So let's let it take care of that pin.
Plone 5.2: https://github.com/zopefoundation/Zope/blob/bcb337eee5cc78a77636d6b2f9d5e558d6b578d5/versions.cfg#L36
Plone 5.1: https://dist.plone.org/versions/zope-2-13-30-versions.cfg
Plone 4.3: https://dist.plone.org/versions/zope-2-13-30-versions.cfg
=> Unpinned configparser in Plone 5.2, 5.1 and 4.3

plone-5.2.x.cfg, plone-5.x.cfg, qa.cfg
`coverage` is already pinned in Plone < 5.2. So we pin it only to `plone-5.2.x.cfg`.
`check-manifest` is already pinned in Plone 5.2. In Plone < 5.2 it is already pinned in `plone-x.x.x.cfg`. So it is not necessary to pin on `qa.cfg`. See:
https://github.com/collective/buildout.plonetest/blob/e728743e79e3f28e310191f82c435c30ccd0e034/plone-5.1.x.cfg#L17
https://github.com/collective/buildout.plonetest/blob/e728743e79e3f28e310191f82c435c30ccd0e034/plone-5.0.x.cfg#L18
https://github.com/collective/buildout.plonetest/blob/37a8da2ef56cadc465380c0896b706bb04ae926d/plone-4.3.x.cfg#L20
=> Fixes pins of coverage and check-manifest in Python 2

plone-5.0.x.cfg
`contextlib2` > 0.6.0.post1 is not compatible with Python 2. See:
https://github.com/jazzband/contextlib2/blob/21.6.0/setup.py#L25
Zope from other versions of Plone already pin `contextlib2` compatible with Python 2. See:
https://github.com/zopefoundation/Zope/blob/4.6.3/versions.cfg#L36
=> Pinn contextlib2 = 0.6.0.post1 in Plone 5.0

qa.cfg
Sometimes the ``i18ndude`` command fails but ``rebuild_i18n.sh`` returns 0. We use ``rebuild_i18n.sh`` on our CI to verify that all translations have been add. The build was passing, even with the ``i18ndude`` error. With ``#! /bin/sh -e`` rebuild_i18n.sh will stop running when an error occurs and return 1.
=> Make rebuild_i18n.sh fail if i18ndude fail

plone-6.0.x.cfg
There is nothing there for us.
Should be fine to remove in Plone 4 and 5 as well, but let's err on the safe side.
=> Removed https://dist.plone.org/thirdparty/ from find-links in Plone 6.

plone-5.1.x.cfg
Pin `bleach = 3.3.1` and `pyparsing = 2.4.7`, which are Python 2 compatible `zest.releaser` dependencies.
=> Pin zest.releaser dependencies in Plone 5.1

qa.cfg
These are the latest `Python 2.7` compatible versions.
See:
https://github.com/jbkahn/flake8-debugger#400---2020-11-29
https://github.com/jbkahn/flake8-print#400---2020-11-29
=> Pinn flake8-debugger = 3.2.1 and flake8-print = 3.1.4 in Python 2.7

qa.cfg
flake8-plone-hasattr = 0.2
flake8-plone-api = 1.4
flake8-pep3101 = 1.3.0
flake8-deprecated= 1.3
New versions of this packages are not compatible with Python 2.
=> Pin Python 2 compatible versions of flake8 plugin packages
